## Episódio 1

In [1]:
3 + 5 * 4

23

In [2]:
peso_kg = 15 * 4

In [3]:
peso_kg * .9

54.0

In [4]:
lanchonete = "Bob's"

In [5]:
lanchonete

"Bob's"

In [6]:
jogador = 'Edson "Pelé" do Nascimento'

In [7]:
jogador

'Edson "Pelé" do Nascimento'

In [8]:
peso_kg

60

In [9]:
print(peso_kg)

60


In [10]:
lanchonete

"Bob's"

In [11]:
print(lanchonete)

Bob's


In [12]:
jogador

'Edson "Pelé" do Nascimento'

In [13]:
x = '60'

In [14]:
y = 60

In [15]:
x + lanchonete

"60Bob's"

In [16]:
print(x)

60


In [17]:
print(y)

60


In [18]:
x

'60'

In [19]:
y

60

In [20]:
print(x, y)

60 60


In [21]:
print(jogador, peso_kg)

Edson "Pelé" do Nascimento 60


In [22]:
texto_peso = 'peso em kilogramas:'

In [23]:
print(texto_peso, peso_kg)

peso em kilogramas: 60


In [24]:
print('peso em libras:', peso_kg * 2.2)

peso em libras: 132.0


In [25]:
peso_kg

60

In [26]:
peso_kg = 65
print('peso em kg agora é:', peso_kg)

peso em kg agora é: 65


In [27]:
peso_kg

65

In [28]:
peso_lb = 2.2 * peso_kg

In [29]:
print(texto_peso, peso_kg, 'e em libras:', peso_lb)

peso em kilogramas: 65 e em libras: 143.0


In [30]:
peso_kg = 100.0

In [31]:
print('o peso em kg agora é:', peso_kg, 'mas o peso em lb continua:', peso_lb)

o peso em kg agora é: 100.0 mas o peso em lb continua: 143.0


In [32]:
print (1)

1


In [33]:
coord = -23, -46

In [34]:
coord

(-23, -46)

In [35]:
lat, lon = coord

In [36]:
lat

-23

In [37]:
lon

-46

In [38]:
first, second = 'Grace', 'Hopper'

In [39]:
third, fourth = second, first

In [40]:
print(third, fourth)

Hopper Grace


In [41]:
print

<function print>

In [42]:
print(8888)

8888


## Episódio 2

In [43]:
import numpy

In [45]:
data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [46]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [47]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [48]:
texto_peso

'peso em kilogramas:'

In [50]:
print(texto_peso)

peso em kilogramas:


In [51]:
type(1)

int

In [52]:
type(1.)

float

In [53]:
type('pizza')

str

In [54]:
type(data)

numpy.ndarray

In [55]:
data.shape

(60, 40)

In [56]:
data[0, 0]

0.0

In [57]:
data[30, 20]

13.0

In [58]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [59]:
data[0, 2]

1.0

In [60]:
data[0:4, 0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [61]:
data[0:3, 0:2]

array([[0., 0.],
       [0., 1.],
       [0., 1.]])

In [62]:
data[5:10, 0:10]

array([[0., 0., 1., 2., 2., 4., 2., 1., 6., 4.],
       [0., 0., 2., 2., 4., 2., 2., 5., 5., 8.],
       [0., 0., 1., 2., 3., 1., 2., 3., 5., 3.],
       [0., 0., 0., 3., 1., 5., 6., 5., 5., 8.],
       [0., 1., 1., 2., 1., 3., 5., 3., 5., 8.]])

In [63]:
data[5:10, 7:10]

array([[1., 6., 4.],
       [5., 5., 8.],
       [3., 5., 3.],
       [5., 5., 8.],
       [3., 5., 8.]])

In [81]:
data[:3, 38:]

array([[0., 0.],
       [0., 1.],
       [1., 1.]])

In [65]:
data.shape

(60, 40)

In [66]:
numpy.mean(data)

6.14875

In [67]:
import time
time.ctime()

'Thu Jun 18 21:29:05 2020'

In [77]:
time.ctime()

'Thu Jun 18 21:31:40 2020'